/* CUSTOMERS TABLOSUNDAN A HARFÝ ÝLE BAÞLAYAN KÝÞÝLER 
SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE 'A%' */

/* CUSTOMERS TABLOSUNDAN ADI A HARFÝ ÝLE BAÞLAYAN ERKEK MÜÞTERÝLERÝ ÇEK 
SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE 'A%' AND GENDER = 'E' */

/* 1990 VE 1995 YILLARI ARASINDA DOÐAN MÜÞTERÝLERÝ ÇEKÝNÝZ. 1990 VE 1995 YILLARI DAHÝLDÝR 

SELECT * FROM CUSTOMERS
WHERE BIRTHDATE BETWEEN '1990-01-01' AND  '1995-12-31' */

/* ÝSTANBULDA YAÞAYAN KÝÞÝLERÝ JOÝN KULLANARAK GETÝREN SORGU */
SELECT C.*, CT.CITIES FROM CUSTOMERS C
INNER JOIN CITIES CT ON C.CITYID = CT.ID
WHERE CT.CITIES = 'ÝSTANBUL'